export const ERROR_CODES = {
  SERVER_ERROR: "SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  BASE_INVALID_ACCESS_TOKEN: "BASE_INVALID_ACCESS_TOKEN",
  BASE_AUTH_TOKEN_REQUIRED: "BASE_AUTH_TOKEN_REQUIRED",
  BASE_TOKEN_EXPIRED: "BASE_TOKEN_EXPIRED",
} as const;